name: Update cacert
on:
  workflow_dispatch:
  schedule:
    - cron:  '52 2 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout previous release
        uses: actions/checkout@v2
        with:
          ref: releases
          path: prev_release
          fetch-depth: 0
      - name: Update cacert
        env:
          BUILD_PRIVATE_KEY: ${{ secrets.BUILD_PRIVATE_KEY }}
        run: |
          php tools/updatecert.php
      - name: Setup git credentials
        run: |
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Commit to releases repo
        run: |
          cp release/* prev_release/ || true
          ls -la prev_release/
          ls -la release/
          cd prev_release
          git add .
          git status
          git commit -m "Update cacert" || true
          git push
