
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build downloader
        env:
          BUILD_PRIVATE_KEY: ${{ secrets.BUILD_PRIVATE_KEY }}
        run: |
          export BUILD_VERSION=`git describe --tags`
          echo Building \"$BUILD_VERSION\"
          php _build.php

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Downloader
          path: wp_downloader.php
  
#TODO:
# start php test sever
# run test_wp_downloader.php self-test script from main
# run test_wp_downloader.php from releases branch (TODO: add also test_wp_downaldoer.php to releases branch)
